apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: rootpassword
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-pv-storage
            mountPath: /var/lib/mysql
     
---
apiVersion: v1
kind: Service

metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      # nodePort: 30000

