apiVersion: apps/v1
kind: Deployment

metadata:
  name: node-hello
  labels:
    app: node-hello-app

spec:
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
        - name: hellonode
          image: bromx/mysqlnode:latest
          
          env:
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-password
            - name: "MYSQL_HOST"
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key:  database_url
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key:  database_port
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service

metadata:
  name: nodehello-service

spec:
  selector:
    app: node-hello-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
      nodePort: 30001

